### ISSUE TITLE
Empty Settings Page

### ISSUE THREAD

**Issue by baraary** [MateriiApps/OpenCord#124]
Is the Settings page supposed to be empty? It just shows me a blank page:

![Screenshot_20230318-192855.png](https://user-images.githubusercontent.com/4853984/226117046-db5f2785-737e-4de3-a72e-80d93c60ab11.png)

**Comment by X1nto** [comment]
Yes. It's work-in-progress.

**Comment by rushiiMachine** [comment]
> Is the Settings page supposed to be empty?

yes
