### ISSUE TITLE
Media embed links are not shown

### ISSUE THREAD

**Issue by marshallovski** [MateriiApps/OpenCord#130]
I using OpenCord on Android 13. See the screenshots. This affects video and pictures that posted as link (https://example.com/vid.mp4).
![Screenshot_2023-04-08-09-21-01-85_ee57945a167018b88d446988c2902ad4](https://user-images.githubusercontent.com/68496774/230708965-e595770a-97ac-467a-bad7-fe4a212b9992.jpg)
![Screenshot_2023-04-08-09-20-03-22_ee57945a167018b88d446988c2902ad4](https://user-images.githubusercontent.com/68496774/230708967-fbdaf010-994b-45a3-99a2-ec01ecd597a3.jpg)
![Screenshot_2023-04-08-09-16-56-06_ee57945a167018b88d446988c2902ad4](https://user-images.githubusercontent.com/68496774/230708968-65c43b46-269f-447d-871a-52041d1f91af.jpg)

**Comment by rushiiMachine** [comment]
content rendering is not complete yet and is planned
