### ISSUE TITLE
maybe newb issues

### ISSUE THREAD

**Issue by dialupdoll** [MateriiApps/OpenCord#138]
nightly link doesn't work, unsure how to compile as no guide to dependencies. new to kotlin/gradle so no path to figuring out how to use it, despite wanting to

**Comment by X1nto** [comment]
> unsure how to compile as no guide to dependencies.
![image](https://github.com/MateriiApps/OpenCord/assets/48173186/8441db12-b599-4c92-9249-6a46645edaf7)
