### ISSUE TITLE
Nightly build not available #139

### ISSUE THREAD

**Issue by JinToSek** [MateriiApps/OpenCord#141]
Nightly build not available #139 

![SmartSelect_20230801_092341_Chrome](https://github.com/MateriiApps/OpenCord/assets/141120593/7705b652-77c4-43d1-8b7e-fd49d72996ec)

![SmartSelect_20230801_092341_Chrome](https://github.com/MateriiApps/OpenCord/assets/141120593/4cbbded5-e3af-4409-8067-893ea3fe9f34)

**Comment by rushiiMachine** [comment]
duplicate #139
