### ISSUE TITLE
Sidebars should layer ABOVE the main chat, not BELOW

### ISSUE THREAD

**Issue by JapanYoshi** [MateriiApps/OpenCord#142]
Ever since Tabs UI, Discord has made the horrible decision of putting the main chat window OVER the sidebars, so that the whole screen has to move and rerender to reveal the sidebars. This adds an unnecessary amount of motion that you cannot disable in the settings.

The sidebars should be drawn ABOVE the main chat view, not below.

**Comment by X1nto** [comment]
That UI existed since, idk, 2019? 2018?

Also, drawing sidebars on top would result in the exact same set of motions, I'm not sure what you're getting at

**Comment by JapanYoshi** [comment]
An old design that’s bad is still bad design.

Not only did Discord break a very important UI convention by inverting foreground and background, they also gave lots of their users vertigo by always starting by moving 100% of the screen when opening the sidebar, as opposed to sliding in the new element. That is, instead of moving the new material into view, it moves the world out of view. If you get carsick or seasick, opening the sidebar on Discord feels the same.

**Comment by rushiiMachine** [comment]
yeah sorry this is mimicking the android legacy app and not going to change

**Comment by K4sum1** [comment]
> yeah sorry this is mimicking the android legacy app and not going to change

Remove the Material You in it.

**Comment by X1nto** [comment]
> > yeah sorry this is mimicking the android legacy app and not going to change
> 
> Remove the Material You in it.

Material You is literally in our name
