### ISSUE TITLE
Can't do anything

### ISSUE THREAD

**Issue by vytskalt** [MateriiApps/OpenCord#60]
I logged in and this is what I see
![Screenshot_20220707-001750_OpenCord](https://user-images.githubusercontent.com/35194709/177645140-5a3b74ed-2a69-4e2f-95fb-72cdaba97c87.png)
Nothing loads up

**Comment by DiamondMiner88** [comment]
its a recent debug apk
Please upload a logcat

**Comment by VytskaLT** [comment]
Sorry for the delay, wasn't home
[logcat.txt](https://github.com/MateriApps/OpenCord/files/9079749/logcat.txt)

**Comment by VytskaLT** [comment]
Sorry for the delay, wasn't home
[logcat.txt](https://github.com/MateriApps/OpenCord/files/9079756/logcat.txt)
I removed the part which leaked some stuff, hopefully that's fine?

**Comment by Suburbanno** [comment]
I have the same problem using the [latest version](https://github.com/MateriApps/OpenCord/actions/runs/2578797205)
![Screenshot_20220710-171301_OpenCord](https://user-images.githubusercontent.com/13632826/178160712-c7e7e5ac-5298-44fc-a082-b64caee0cc4e.png)

**Comment by X1nto** [comment]
> Sorry for the delay, wasn't home [logcat.txt](https://github.com/MateriApps/OpenCord/files/9079756/logcat.txt) I removed the part which leaked some stuff, hopefully that's fine?

Could you re-add the parts you removed? OpenCord logger automatically censors tokens, so there's nothing to be afraid about when posting the logcats.
![image](https://user-images.githubusercontent.com/48173186/178160931-9c8f2b06-e9be-456d-93db-b28254d3f765.png)

**Comment by VytskaLT** [comment]
> Could you re-add the parts you removed? OpenCord logger automatically censors tokens, so there's nothing to be afraid about when posting the logcats.

I only removed a small part where it was json data that was received from Discord servers, don't think that's useful. It contained tons of info about servers I'm in and other stuff. Don't want to send that publicly.

![image](https://user-images.githubusercontent.com/35194709/178162911-2132a805-3a24-4759-b453-3788076663fc.png)

**Comment by X1nto** [comment]
> > Could you re-add the parts you removed? OpenCord logger automatically censors tokens, so there's nothing to be afraid about when posting the logcats.
> 
> I only removed a small part where it was json data that was received from Discord servers, don't think that's useful. It contained tons of info about servers I'm in and other stuff about my account. Don't want to send that publicly.
> 
> ![image](https://user-images.githubusercontent.com/35194709/178162911-2132a805-3a24-4759-b453-3788076663fc.png)

The json with t: READY (the first one) is actually the most useful one out of everything. That event contains all guilds and some user data (which are the ones that fail to load), so we need that json to actually see why everything fails.

**Comment by ItzOnlyAnimal** [comment]
> I only removed a small part where it was json data that was received from Discord servers, don't think that's useful. It contained tons of info about servers I'm in and other stuff about my account. Don't want to send that publicly.

If you prefer, you can send/DM it on discord (in Readme) instead of posting it in a github issue. :P

**Comment by Gersonzao** [comment]
I'm still having this issue. Not sure if I should open a new issue for this. Nightly from the README file. Device model is SM-J105B (yes it's that old) running Android 5.1.1
![Screenshot_2022-12-30-00-15-36](https://user-images.githubusercontent.com/85644671/219873952-abfb9eaa-7fa1-433b-91cb-d5e78adb8098.png)
![Screenshot_2022-12-30-00-15-29](https://user-images.githubusercontent.com/85644671/219873953-fe8e34a5-2308-44fc-b67f-8ba156fae439.png)
![Screenshot_2022-12-30-00-15-26](https://user-images.githubusercontent.com/85644671/219873954-0f77a5e0-e179-4157-9647-4d89aa84f044.png)
![Screenshot_2022-12-30-00-15-23](https://user-images.githubusercontent.com/85644671/219873955-eaef4baf-6ccb-4590-8f78-637f76993623.png)

**Comment by rushiiMachine** [comment]
settings, members panel is correct
looks like your client isn't connecting to the gateway for some reason

**Comment by Gersonzao** [comment]
> settings, members panel is correct looks like your client isn't connecting to the gateway for some reason

So... do you think I should open a new issue for that? Never tried disabling I2P or my VPN to see if this gets fixed. I will try that as soon as I am able to

**Comment by rushiiMachine** [comment]
probably
whatever your traffic is going through it's not ending up at discord

not really our fault
