### ISSUE TITLE
Is OpenCord a rat?

### ISSUE THREAD

**Issue by EnderPlays25** [MateriiApps/OpenCord#94]
Trying to login does nothing, any way to fix?

**Comment by DiamondMiner88** [comment]
?????????? is that title
are you going to provide a log

**Comment by EnderPlays25** [comment]
How do I provide a log? I entered my login info and nothing happened

**Comment by EnderPlays25** [comment]
I don't have a computer. Can you show me how to login?

**Comment by DiamondMiner88** [comment]
no log, no solution
