### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by ThatOneCalculator** [MateriiApps/OpenCord#95]
Even when setting my phone to light mode, the app is still in dark mode. As this uses MD3, dark/light mode based on the system theme should be pretty easy.

**Comment by ItzOnlyAnimal** [comment]
the problem is they are in pr hell :trollface: settings are somewhere next i think

**Comment by X1nto** [comment]
I did PR the code for system theme but it seems like I forgot to actually make use of it. Working on a fix now
