### ISSUE TITLE
Each nightly release conflicts with the previous package

### ISSUE THREAD

**Issue by ThatOneCalculator** [MateriiApps/OpenCord#99]
This makes downloading from the nightly link and upgrading a pain, as I have to uninstall the previous version before installing the new one.

**Comment by DiamondMiner88** [comment]
youll have to cope with it for now
this is because the action doesn't sign the apk
which is intentional for security

**Comment by DiamondMiner88** [comment]
If you have root, you can install CorePatch for lsposed and disable signature checks for apks
